{{- if .Values.hpa -}}
{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "fullname" . }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ template "fullname" . }}
    apiVersion: "apps/v1"
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.hpa.targetCPUAverageUtilization }}
{{ end -}}
{{ end -}}
