{{- if and .Values.api.enabled (or .Values.api.loadbalancer .Values.api.portLevelSettings) }}
{{- $svc := include ".servicename" . }}
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: {{ $svc }}
spec:
  {{- if .Values.api.loadbalancer }}
  loadbalancer:
    type: {{ $.Values.api.loadbalancer | quote }}
  {{- else }}
  portLevelSettings: {{ toYaml $.Values.api.portLevelSettings | nindent 4 }}
  {{- end }}
{{- end }}