{{- if .Values.api.enabled }}
{{- $svc := include ".servicename" . }}
{{- $canary := .Values.canary.enabled }}
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ $svc }}
spec:
  http:
  {{- range $key , $route := .Values.api.routes }}
  - name: {{ $svc }}-{{ $key }}
    match:
      {{- if $route.hosts }}
      hosts: {{ toYaml $route.hosts | nindent 6 }}
      {{- end }}
      {{- if $route.paths }}
      paths: {{ toYaml $route.paths | nindent 6 }}
      {{- else }}
      paths: "/{{ $svc }}/*"
      {{- end }}
    backends:
      - {{- if $route.service }}
        servicePort: {{ default 80 $route.service.port }}
        {{- else }}
        servicePort: 80
        {{- end }}
        {{- if $canary }}
        serviceName: {{ $svc }}-primary
        {{- else }}
        serviceName: {{ $svc }}
        {{- end }}
    plugin_config_name: hydra-apc
    plugins:
    {{- range $route.plugins }}
      - name: {{ .name }}
        enable: true
        config: {{ toYaml .config | nindent 10 }}
    {{- end }}
  {{- end }}
{{- end }}